/* No remote-control bridge: iPad actions never operate Mac applications. */
window.TODAY_COMPANION = true;
document.body.classList.add('companion-loading');
const companionStatus = document.createElement('div');
companionStatus.id = 'companion-status';
const companionMessage = document.createElement('span');
companionMessage.setAttribute('role', 'status');
const companionUpdate = document.createElement('button');
companionUpdate.type = 'button';
companionUpdate.id = 'companion-update';
companionUpdate.textContent = 'Update dashboard';
companionUpdate.title = 'Load the latest dashboard from your Mac. Your timer and settings stay saved.';
companionStatus.append(companionMessage, companionUpdate);
companionUpdate.addEventListener('click', async () => {
  companionUpdate.disabled = true;
  try {
    const response = await fetch('/dashboard', {cache: 'no-store', signal: AbortSignal.timeout(8000)});
    if (response.status === 401 || response.status === 403) {
      companionMessage.textContent = 'Pair again using the QR code in Today’s Mac settings to load this update.';
      return;
    }
    if (!response.ok) throw Error();
    window.location.reload();
  } catch {
    companionMessage.textContent = 'Start sharing in Today on your Mac, then scan its QR code to reconnect and update.';
  } finally { companionUpdate.disabled = false; }
});
document.body.prepend(companionStatus);
let companionLoaded = false;
let companionBusy = false;
let companionLastScript = '';
function companionUnavailable() {
  alert('Open this item in Mail or Calendar on your Mac. This companion displays a read-only view.');
}
window.webkit = {messageHandlers: {
  calendarRefresh: {postMessage: () => companionRefresh()},
  mailOpen: {postMessage: companionUnavailable},
  mailOpenApp: {postMessage: companionUnavailable},
  respondInCalendar: {postMessage: companionUnavailable},
  openSettings: {postMessage: () => alert('Manage connections and sharing in Today on your Mac.')}
}};
async function companionRefresh() {
  if (companionBusy) return;
  companionBusy = true;
  try {
    const response = await fetch('/snapshot', {cache: 'no-store', signal: AbortSignal.timeout(8000)});
    if (response.status === 401 || response.status === 403) {
      document.querySelector('.page')?.remove();
      companionMessage.textContent = 'Pairing expired. Scan a new QR code from Today on your Mac.';
      return;
    }
    if (!response.ok) throw Error();
    const source = await response.text();
    if (source !== companionLastScript || !companionLoaded) {
      // Same-origin authenticated source, generated by Today and the user's local schedule files.
      (0, eval)(source);
      companionLastScript = source;
      if (!companionLoaded) {
        await new Promise((resolve, reject) => {
          const script = document.createElement('script');
          script.src = '/app.js'; script.onload = resolve; script.onerror = reject;
          document.body.append(script);
        });
        companionLoaded = true;
        document.body.classList.remove('companion-loading');
      } else window.refreshLocalDashboard();
    }
    const stamp = window.DASHBOARD_DATA?.generatedAt;
    const stale = !stamp || Date.now() - new Date(stamp).getTime() > 10 * 60 * 1000;
    companionMessage.textContent = stale
      ? 'Connected · Mac data is older than 10 minutes. Refresh Today on your Mac.'
      : 'Connected to your Mac · Timer stays on this device';
  } catch {
    companionMessage.textContent = companionLoaded
      ? 'Mac unavailable · Showing the last received data. Keep your Mac awake and Today open.'
      : 'Waiting for your Mac · Keep Today open, choose a calendar, and check that both devices are on the same Wi-Fi.';
  } finally { companionBusy = false; }
}
window.addEventListener('today:updated', () => {
  document.querySelectorAll('.invite-mail-action').forEach(button => {
    button.disabled = true; button.textContent = 'Respond on your Mac';
  });
});
companionRefresh();
setInterval(companionRefresh, 15000);
window.addEventListener('online', companionRefresh);
document.addEventListener('visibilitychange', () => { if (!document.hidden) companionRefresh(); });
